### ISSUE TITLE
Chapter 2: Using Atom Atom Packages

### ISSUE THREAD

**Issue by jysperm** [atom-china/manual#1]
原文链接：[Atom Packages](http://flight-manual.atom.io/using-atom/sections/atom-packages/)

排版校对：https://github.com/wizardforcel/atom-flight-manual-zh-cn/blob/master/2.1-Atom-Packages.md

**Comment by mzlogin** [comment]
认领。

**Comment by mzlogin** [comment]
Merged, see #31
