### ISSUE TITLE
Chapter 2: Using Atom Snippets

### ISSUE THREAD

**Issue by mzlogin** [atom-china/manual#10]
原文链接：[Snippets](http://flight-manual.atom.io/using-atom/sections/snippets/)

排版校对：https://github.com/wizardforcel/atom-flight-manual-zh-cn/blob/master/2.6-Snippets.md

**Comment by chenxiaoyoyo** [comment]
认领

**Comment by mzlogin** [comment]
@chenxiaoyoyo 认领成功。

**Comment by mzlogin** [comment]
Merged #33
