### ISSUE TITLE
Chapter 2: Using Atom Autocomplete

### ISSUE THREAD

**Issue by mzlogin** [atom-china/manual#11]
原文链接：[Autocomplete](http://flight-manual.atom.io/using-atom/sections/autocomplete/)

排版校对：https://github.com/wizardforcel/atom-flight-manual-zh-cn/blob/master/2.7-Autocomplete.md

**Comment by DeadLion** [comment]
认领
感觉有些小节字数很少啊，可以一次翻好几个。

**Comment by mzlogin** [comment]
收到，认领成功 @DeadLion 😄 可以嗖嗖地翻完接着下一个 👍
