### ISSUE TITLE
Chapter 2: Using Atom Folding

### ISSUE THREAD

**Issue by mzlogin** [atom-china/manual#12]
原文链接：[Folding](http://flight-manual.atom.io/using-atom/sections/folding/)

排版校对：https://github.com/wizardforcel/atom-flight-manual-zh-cn/blob/master/2.8-Folding.md

**Comment by chenxiaoyoyo** [comment]
评论~~

**Comment by mzlogin** [comment]
@chenxiaoyoyo 认领成功，文章里的图片记得使用原文里最新的~ :smile:

**Comment by mzlogin** [comment]
Merged #28
