### ISSUE TITLE
Chapter 2: Using Atom Panes

### ISSUE THREAD

**Issue by mzlogin** [atom-china/manual#13]
原文链接：[Panes](http://flight-manual.atom.io/using-atom/sections/panes/)

排版校对：https://github.com/wizardforcel/atom-flight-manual-zh-cn/blob/master/2.9-Panes.md

**Comment by zxning** [comment]
认领

**Comment by mzlogin** [comment]
@zxning 认领成功。

**Comment by mzlogin** [comment]
Merged in #30
