### ISSUE TITLE
有个疑问

### ISSUE THREAD

**Issue by DeadLion** [atom-china/manual#20]
已经有人翻译了，而且质量还不错，那我们为什么还要再翻译一遍呢？

**Comment by jysperm** [comment]
https://github.com/guo-yu/atom-guide 这个的话我很久之前就注意到了，不过这个翻译是在 Atom 发布没多久的时候，部分内容已经过时了。

https://github.com/wizardforcel/atom-flight-manual-zh-cn 这个的话我是最近才发现的，它似乎是从这个仓库  fork 过来的，或许我们应该联系一下这位作者将内容做一下合并，一起维护？ @mzlogin

**Comment by mzlogin** [comment]
@DeadLion 这是我的失误。我前不久已然发现了 wizardforcel 维护的已翻译大部分章节的仓库，但当时纠结了一下合并其版本可能需要转变 LICENSE 的问题，并没有及时推进引用合并。其实细想一下这是小事，分别联系一下维护者和 @jysperm 征求一个大家都认可的方案即可。

@jysperm 为了避免重复劳动，确实应该如此，是我没有及时推进。

我已经去 wizardforcel 的仓库发了 [Issue](https://github.com/wizardforcel/atom-flight-manual-zh-cn/issues/4)，等作者回复之后我们再看下一步如何进行吧，我先将翻译认领章节状态修改一下暂停进度。

**Comment by mzlogin** [comment]
@jysperm 作者在 Issue 里已经回复，我们可以合并他的内容，如果采用与他的仓库相同的 [CC BY-NC-SA 3.0](http://creativecommons.org/licenses/by-nc-sa/3.0/cn/) LICENSE 更好，如果不是也 OK。

我个人的看法是作为一个社区维护的文档翻译类项目，Atom 官方文档采用的是 [CC BY-SA 3.0](http://creativecommons.org/licenses/by-sa/3.0/)，咱们用 CC BY-NC-SA 3.0 比 MIT 更合适一点。

你对采用哪个 LICENSE 怎么看？

**Comment by jysperm** [comment]
按照 CC BY-SA 的条款，所有衍生作品都 **必须** 使用相同协议来发布。
确实这个项目的 MIT 是我建项目的时候没仔细考虑就加上的。

**Comment by mzlogin** [comment]
那我跟仓主商量下使用 CC BY-SA 3.0 吧

**Comment by mzlogin** [comment]
已跟仓主达成一致，使用 CC BY-SA。
