### ISSUE TITLE
Chapter 5: Upgrading to 1.0 APIs Upgrading Your Syntax Theme

### ISSUE THREAD

**Issue by mzlogin** [atom-china/manual#23]
原文链接：[Upgrading Your Syntax Theme](http://flight-manual.atom.io/upgrading-to-1-0-apis/sections/upgrading-your-syntax-theme/)

**Comment by 1977744311** [comment]
认领

**Comment by mzlogin** [comment]
@1977744311 可以的少年~建议翻译前先看一下 README，里面有一些说明和现成的资源，能用上的尽量用上，避免重复劳动。

那我就分给你啦~

**Comment by mzlogin** [comment]
@1977744311 认领成功

**Comment by 1977744311** [comment]
以PR 链接https://github.com/1977744311/manual/tree/translate
