### ISSUE TITLE
Chapter 2: Using Atom Writing in Atom

### ISSUE THREAD

**Issue by mzlogin** [atom-china/manual#29]
原文链接：[Writing in Atom](http://flight-manual.atom.io/using-atom/sections/writing-in-atom/)

排版校对：https://github.com/wizardforcel/atom-flight-manual-zh-cn/blob/master/2.12-Writing-in-Atom.md

**Comment by zxning** [comment]
认领

**Comment by mzlogin** [comment]
@zxning 认领成功。

**Comment by mzlogin** [comment]
Merged #38
