### ISSUE TITLE
Chapter 1: Getting Started Summary

### ISSUE THREAD

**Issue by mzlogin** [atom-china/manual#4]
原文链接：[Summary](http://flight-manual.atom.io/getting-started/sections/summary/)

校对链接：#8

**Comment by equt** [comment]
**校对认领** @mzlogin

**Comment by mzlogin** [comment]
收到～ @Wolther47  多谢

**Comment by equt** [comment]
校对完毕 。。。 @mzlogin 已经Pr

**Comment by mzlogin** [comment]
Merged
