### ISSUE TITLE
Chapter 2: Using Atom Atom Selections

### ISSUE THREAD

**Issue by mzlogin** [atom-china/manual#6]
原文链接：[Atom Selections](http://flight-manual.atom.io/using-atom/sections/atom-selections/)

校对链接：#15

**Comment by hypogaea** [comment]
我是想试试，但是Git命令行操作还不很熟悉。。。

**Comment by mzlogin** [comment]
可以趁此机会顺便熟悉 Git 的操作和工作流。

使用 Git 也不一定非得命令行，GitHub 有各平台的客户端，大部分操作都可以直接在界面上完成。 

非常欢迎和期待你的加入！@hypogaea :smile:

**Comment by hypogaea** [comment]
认领

**Comment by hypogaea** [comment]
认领

**Comment by mzlogin** [comment]
收到~ @hypogaea 认领成功。
