### ISSUE TITLE
Chapter 2: Using Atom Editing and Deleting Text

### ISSUE THREAD

**Issue by mzlogin** [atom-china/manual#7]
原文链接：[Editing and Deleting Text](http://flight-manual.atom.io/using-atom/sections/editing-and-deleting-text/)

校对链接：#18

**Comment by hypogaea** [comment]
认领

**Comment by mzlogin** [comment]
收到~ @hypogaea 认领成功！

**Comment by mzlogin** [comment]
你的上一篇翻译合入后主干文件结构有重构，请在继续翻译前先合入主干的更改，或者直接重新 Fork 主干。 @hypogaea :smile:

**Comment by hypogaea** [comment]
好的，知道啦！@mzlogin
